// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Aula struct {
	ID          int32
	TabletID    int32
	ProfessorID int32
	RoomID      int32
	StudentName string
	Observation string
	MeetStart   time.Time
	MeetEnd     time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Professor struct {
	ID         int32
	Name       string
	LabelColor string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Room struct {
	ID         int32
	Name       string
	LabelColor string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Session struct {
	ID           uuid.UUID
	Email        string
	RefreshToken string
	UserAgent    string
	ClientIp     string
	IsBlocked    bool
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

type Tablet struct {
	ID         int32
	Name       string
	LabelColor string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
