// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: professors.sql

package sqlc

import (
	"context"
	"time"
)

const createProfessor = `-- name: CreateProfessor :one
INSERT INTO professors (name, label_color) VALUES ($1, $2) RETURNING id, name, label_color, created_at, updated_at
`

type CreateProfessorParams struct {
	Name       string `json:"name"`
	LabelColor string `json:"labelColor"`
}

func (q *Queries) CreateProfessor(ctx context.Context, arg CreateProfessorParams) (Professor, error) {
	row := q.db.QueryRowContext(ctx, createProfessor, arg.Name, arg.LabelColor)
	var i Professor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LabelColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfessorByID = `-- name: DeleteProfessorByID :exec
DELETE FROM professors WHERE id = $1
`

func (q *Queries) DeleteProfessorByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteProfessorByID, id)
	return err
}

const getProfessorByID = `-- name: GetProfessorByID :one
SELECT id, name, label_color, created_at, updated_at FROM professors WHERE id = $1
`

func (q *Queries) GetProfessorByID(ctx context.Context, id int32) (Professor, error) {
	row := q.db.QueryRowContext(ctx, getProfessorByID, id)
	var i Professor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LabelColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAvailableProfessorsByTimeRange = `-- name: ListAvailableProfessorsByTimeRange :many
SELECT id, name, label_color, created_at, updated_at
FROM professors
WHERE id NOT IN (SELECT professor_id
                 FROM aulas a
                 WHERE (meet_start >= $1 AND meet_end   <= $2 OR
                        meet_end   >= $1 AND meet_start <= $2)
                   AND professor_id IS NOT NULL)
`

type ListAvailableProfessorsByTimeRangeParams struct {
	MeetStart time.Time `json:"meetStart"`
	MeetEnd   time.Time `json:"meetEnd"`
}

func (q *Queries) ListAvailableProfessorsByTimeRange(ctx context.Context, arg ListAvailableProfessorsByTimeRangeParams) ([]Professor, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableProfessorsByTimeRange, arg.MeetStart, arg.MeetEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Professor{}
	for rows.Next() {
		var i Professor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LabelColor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfessors = `-- name: ListProfessors :many
SELECT count(*) OVER () AS total_items, sub_query.id, sub_query.name, sub_query.label_color, sub_query.created_at, sub_query.updated_at FROM
    (SELECT id, name, label_color, created_at, updated_at FROM professors ORDER BY CASE
        WHEN NOT $3::bool AND $4::text = 'name' THEN name
      END ASC, CASE
        WHEN $3::bool AND $4::text = 'name' THEN name
      END DESC, CASE
        WHEN NOT $3::bool AND $4::text = 'id' THEN id
     END ASC, CASE
       WHEN $3::bool AND $4::text = 'id' THEN id
     END DESC)
        sub_query LIMIT $1 OFFSET $2
`

type ListProfessorsParams struct {
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
	Reverse bool   `json:"reverse"`
	OrderBy string `json:"orderBy"`
}

type ListProfessorsRow struct {
	TotalItems int64     `json:"totalItems"`
	ID         int32     `json:"id"`
	Name       string    `json:"name"`
	LabelColor string    `json:"labelColor"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

func (q *Queries) ListProfessors(ctx context.Context, arg ListProfessorsParams) ([]ListProfessorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfessors,
		arg.Limit,
		arg.Offset,
		arg.Reverse,
		arg.OrderBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfessorsRow{}
	for rows.Next() {
		var i ListProfessorsRow
		if err := rows.Scan(
			&i.TotalItems,
			&i.ID,
			&i.Name,
			&i.LabelColor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfessorByID = `-- name: UpdateProfessorByID :one
UPDATE professors SET name = $2, label_color = $3 WHERE id = $1 RETURNING id, name, label_color, created_at, updated_at
`

type UpdateProfessorByIDParams struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	LabelColor string `json:"labelColor"`
}

func (q *Queries) UpdateProfessorByID(ctx context.Context, arg UpdateProfessorByIDParams) (Professor, error) {
	row := q.db.QueryRowContext(ctx, updateProfessorByID, arg.ID, arg.Name, arg.LabelColor)
	var i Professor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LabelColor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
