// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateAula(ctx context.Context, arg CreateAulaParams) (Aula, error)
	CreateProfessor(ctx context.Context, arg CreateProfessorParams) (Professor, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateTablet(ctx context.Context, arg CreateTabletParams) (Tablet, error)
	DeleteAulaByID(ctx context.Context, id int32) (Aula, error)
	DeleteProfessorByID(ctx context.Context, id int32) (Professor, error)
	DeleteRoomByID(ctx context.Context, id int32) (Room, error)
	DeleteTabletByID(ctx context.Context, id int32) (Tablet, error)
	GetAulaByID(ctx context.Context, id int32) (Aula, error)
	GetProfessorByID(ctx context.Context, id int32) (Professor, error)
	GetRoomByID(ctx context.Context, id int32) (Room, error)
	GetTabletByID(ctx context.Context, id int32) (Tablet, error)
	ListAulas(ctx context.Context) ([]Aula, error)
	ListAulasByTimeRange(ctx context.Context, arg ListAulasByTimeRangeParams) ([]ListAulasByTimeRangeRow, error)
	ListAvailableProfessorsByTimeRange(ctx context.Context, arg ListAvailableProfessorsByTimeRangeParams) ([]Professor, error)
	ListAvailableRoomsByTimeRange(ctx context.Context, arg ListAvailableRoomsByTimeRangeParams) ([]Room, error)
	ListAvailableTabletsByTimeRange(ctx context.Context, arg ListAvailableTabletsByTimeRangeParams) ([]Tablet, error)
	ListProfessors(ctx context.Context, arg ListProfessorsParams) ([]ListProfessorsRow, error)
	ListRooms(ctx context.Context, arg ListRoomsParams) ([]ListRoomsRow, error)
	ListTablets(ctx context.Context, arg ListTabletsParams) ([]ListTabletsRow, error)
	UpdateAulaByID(ctx context.Context, arg UpdateAulaByIDParams) (Aula, error)
	UpdateProfessorByID(ctx context.Context, arg UpdateProfessorByIDParams) (Professor, error)
	UpdateRoomByID(ctx context.Context, arg UpdateRoomByIDParams) (Room, error)
	UpdateTabletByID(ctx context.Context, arg UpdateTabletByIDParams) (Tablet, error)
}

var _ Querier = (*Queries)(nil)
