// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: tablets.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTablet = `-- name: CreateTablet :execresult
INSERT INTO tablets (name) VALUES ($1)
`

func (q *Queries) CreateTablet(ctx context.Context, name sql.NullString) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTablet, name)
}

const deleteTabletByID = `-- name: DeleteTabletByID :exec
DELETE FROM tablets WHERE id = $1
`

func (q *Queries) DeleteTabletByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTabletByID, id)
	return err
}

const getTabletByID = `-- name: GetTabletByID :one
SELECT id, name, created_at, updated_at FROM tablets WHERE id = $1
`

func (q *Queries) GetTabletByID(ctx context.Context, id int32) (Tablet, error) {
	row := q.db.QueryRowContext(ctx, getTabletByID, id)
	var i Tablet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAvailableTabletsByTimeRange = `-- name: ListAvailableTabletsByTimeRange :many
SELECT id, name, created_at, updated_at
FROM tablets
WHERE id NOT IN (SELECT tablet_id
                 FROM aulas a
                 WHERE (meet_start >= $1 AND meet_end   <= $2 OR
                        meet_end   >= $1 AND meet_start <= $2)
                   AND tablet_id IS NOT NULL)
`

type ListAvailableTabletsByTimeRangeParams struct {
	MeetStart sql.NullTime `json:"meetStart"`
	MeetEnd   sql.NullTime `json:"meetEnd"`
}

func (q *Queries) ListAvailableTabletsByTimeRange(ctx context.Context, arg ListAvailableTabletsByTimeRangeParams) ([]Tablet, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableTabletsByTimeRange, arg.MeetStart, arg.MeetEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tablet{}
	for rows.Next() {
		var i Tablet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTablets = `-- name: ListTablets :many
SELECT id, name, created_at, updated_at FROM tablets
`

func (q *Queries) ListTablets(ctx context.Context) ([]Tablet, error) {
	rows, err := q.db.QueryContext(ctx, listTablets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tablet{}
	for rows.Next() {
		var i Tablet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTabletByID = `-- name: UpdateTabletByID :execresult
UPDATE tablets SET name = $2 WHERE id = $1
`

type UpdateTabletByIDParams struct {
	ID   int32          `json:"id"`
	Name sql.NullString `json:"name"`
}

func (q *Queries) UpdateTabletByID(ctx context.Context, arg UpdateTabletByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTabletByID, arg.ID, arg.Name)
}
